### ISSUE TITLE
password grant type

### ISSUE THREAD

**Issue by pjebs** [felipeweb/osin-mysql#14]
Does this work with the password grant type?
I don't see in the schema creation any place where it stores username and password

**Comment by felipeweb** [comment]
You can store username and password on client_id and client_secret

**Comment by pjebs** [comment]
That's not the password grant type. Client Id and client secret are different

**Comment by felipeweb** [comment]
Could send a PR?

**Comment by pjebs** [comment]
I actually sent a message here: https://github.com/RangelReale/osin/issues/179

I'm still trying to work out how this library works.
