### ISSUE TITLE
With autogenerated tables on token are not case sensitive

### ISSUE THREAD

**Issue by osavchenko** [felipeweb/osin-mysql#9]
When I execute something like `SELECT client, authorize, previous, access_token, refresh_token, expires_in, scope, redirect_uri, created_at, extra FROM access WHERE access_token="some-token" LIMIT 1` it ignore token letter case. In my project I change column collation to `utf8_bin`. Is it good solution or you know better?
BTW, when we decide how to solve it I can create PR to improve this.

**Comment by felipeweb** [comment]
@osavchenko it is a good improve go ahead
